# Generated by Django 5.2.8 on 2025-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_code',
            field=models.CharField(default='G1', help_text="Student's assigned group code (e.g., G1, G2, G3)", max_length=20),
            preserve_default=False,
        ),
    ]
